# Generated by Django 4.0.4 on 2022-05-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('plate_size', models.IntegerField()),
            ],
        ),
    ]
