# Generated by Django 3.2.5 on 2022-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('plate_size', models.CharField(max_length=10)),
            ],
        ),
    ]
